$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$root = Split-Path -Parent $PSScriptRoot
$res = Join-Path $root 'android\app\src\main\res'
function Draw-DoubleT([System.Drawing.Graphics]$graphics,[int]$x,[int]$y,[int]$size,[System.Drawing.Color]$color){$brush=New-Object System.Drawing.SolidBrush($color);$barWidth=[int]($size*.31);$barHeight=[int]($size*.105);$stemWidth=[int]($size*.105);$stemHeight=[int]($size*.39);$gap=[int]($size*.055);$left=$x+[int]($size*.16);$right=$x+$size-[int]($size*.16)-$barWidth;$top=$y+[int]($size*.25);$graphics.FillRectangle($brush,$left,$top,$barWidth,$barHeight);$graphics.FillRectangle($brush,$left+$barWidth-$stemWidth-$gap,$top+$barHeight,$stemWidth,$stemHeight);$graphics.FillRectangle($brush,$right,$top,$barWidth,$barHeight);$graphics.FillRectangle($brush,$right+$gap,$top+$barHeight,$stemWidth,$stemHeight);$brush.Dispose()}
function Save-Icon([string]$path,[int]$width,[int]$height,[bool]$splash){$bitmap=New-Object System.Drawing.Bitmap($width,$height);$graphics=[System.Drawing.Graphics]::FromImage($bitmap);$graphics.SmoothingMode=[System.Drawing.Drawing2D.SmoothingMode]::AntiAlias;$background=if($splash){[System.Drawing.Color]::FromArgb(7,16,30)}else{[System.Drawing.Color]::FromArgb(237,242,255)};$graphics.Clear($background);$ratio=if($splash){.34}else{1};$size=[int]([Math]::Min($width,$height)*$ratio);Draw-DoubleT $graphics ([int](($width-$size)/2)) ([int](($height-$size)/2)) $size ([System.Drawing.Color]::FromArgb(48,99,235));$bitmap.Save($path,[System.Drawing.Imaging.ImageFormat]::Png);$graphics.Dispose();$bitmap.Dispose()}
$sizes=@{'mdpi'=48;'hdpi'=72;'xhdpi'=96;'xxhdpi'=144;'xxxhdpi'=192}
foreach($density in $sizes.Keys){$dir=Join-Path $res "mipmap-$density";foreach($name in @('ic_launcher.png','ic_launcher_round.png','ic_launcher_foreground.png')){Save-Icon (Join-Path $dir $name) $sizes[$density] $sizes[$density] $false}}
Get-ChildItem -LiteralPath $res -Filter 'splash.png' -Recurse|ForEach-Object{$old=[System.Drawing.Image]::FromFile($_.FullName);$w=$old.Width;$h=$old.Height;$old.Dispose();Save-Icon $_.FullName $w $h $true}
