import {useEffect,useMemo,useState} from 'react';
import {BookOpen,CheckCircle2,Clock3,GraduationCap,LockKeyhole,ShieldCheck,UserRound,Users} from 'lucide-react';
import {getCloudConfig,getCloudSession} from './cloudSync';
import {loadAllocations} from './storage';
import SchoolSuite from './schoolSuite';

type Role='pending'|'teacher'|'student'|'admin';
type Profile={id:string;role:Role;display_name:string;teacher_name?:string;student_number?:string;class_group?:string};
type Assignment={id:number;teacher_id:string;subject:string;class_group:string};
type WindowRow={id:number;subject:string;class_group:string;opens_at:string;closes_at:string;reopened_until?:string};
type Mark={id:number;student_id:string;subject:string;class_group:string;assessment:string;score:number;out_of:number;teacher_id:string};
type RequestRow={id:number;teacher_id:string;subject:string;class_group:string;reason:string;status:string;requested_until?:string};
const clean=(v:string)=>v.toLowerCase().replace(/\b(mr|mrs|miss|ms)\b/g,'').replace(/[^a-z]/g,'');

export default function AcademicPortal(){
 const session=getCloudSession() as {access_token:string;user:{id:string;email?:string}}|null,config=getCloudConfig();
 const [profile,setProfile]=useState<Profile|null>(null),[profiles,setProfiles]=useState<Profile[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[windows,setWindows]=useState<WindowRow[]>([]),[marks,setMarks]=useState<Mark[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[loading,setLoading]=useState(Boolean(session)),[status,setStatus]=useState('');
 const [requestedRole,setRequestedRole]=useState<'teacher'|'student'>('teacher'),[name,setName]=useState(''),[studentNumber,setStudentNumber]=useState(''),[classGroup,setClassGroup]=useState('');
 const [subject,setSubject]=useState(''),[assessment,setAssessment]=useState(''),[score,setScore]=useState(''),[outOf,setOutOf]=useState('100'),[studentId,setStudentId]=useState(''),[teacherId,setTeacherId]=useState('');
 const [openAt,setOpenAt]=useState(''),[closeAt,setCloseAt]=useState(''),[reason,setReason]=useState('');
 const headers=()=>({'apikey':config.key,'Authorization':`Bearer ${session?.access_token||config.key}`,'Content-Type':'application/json','Prefer':'return=representation'});
 const api=async(path:string,options:RequestInit={})=>{const response=await fetch(`${config.url}/rest/v1/${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const body=await response.text();if(!response.ok)throw new Error(body||'Academic request failed.');return body?JSON.parse(body):[]};
 const refresh=async()=>{if(!session)return;setLoading(true);try{const mine=await api(`timekeeper_profiles?id=eq.${session.user.id}&select=*`);setProfile(mine[0]||null);if(mine[0]?.role==='admin'){const [p,a,w,m,r]=await Promise.all([api('timekeeper_profiles?select=*&order=created_at.desc'),api('timekeeper_teacher_subjects?select=*'),api('timekeeper_mark_windows?select=*&order=closes_at.desc'),api('timekeeper_marks?select=*&order=updated_at.desc'),api('timekeeper_window_requests?select=*&order=created_at.desc')]);setProfiles(p);setAssignments(a);setWindows(w);setMarks(m);setRequests(r)}else if(mine[0]?.role==='teacher'){const [a,w,m,r,p]=await Promise.all([api('timekeeper_teacher_subjects?select=*'),api('timekeeper_mark_windows?select=*&order=closes_at.desc'),api('timekeeper_marks?select=*&order=updated_at.desc'),api('timekeeper_window_requests?select=*&order=created_at.desc'),api('timekeeper_profiles?role=eq.student&select=id,display_name,student_number,class_group')]);setAssignments(a);setWindows(w);setMarks(m);setRequests(r);setProfiles(p)}else if(mine[0]?.role==='student')setMarks(await api('timekeeper_marks?select=*&order=subject,assessment'))}catch(error){setStatus(error instanceof Error?error.message:'Academic portal could not load.')}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[session?.user.id]);
 const register=async()=>{if(!session||!name.trim())return;try{await api('timekeeper_profiles',{method:'POST',body:JSON.stringify({id:session.user.id,role:'pending',display_name:name.trim(),teacher_name:requestedRole==='teacher'?name.trim():null,student_number:requestedRole==='student'?studentNumber.trim():null,class_group:requestedRole==='student'?classGroup.trim():null})});setStatus(`Your ${requestedRole} access request is waiting for administrator approval.`);await refresh()}catch(error){setStatus(error instanceof Error?error.message:'Request failed.')}};
 const approve=async(p:Profile,role:Role)=>{await api(`timekeeper_profiles?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({role})});await refresh()};
 const allocate=async()=>{if(!teacherId||!subject||!classGroup)return;await api('timekeeper_teacher_subjects',{method:'POST',body:JSON.stringify({teacher_id:teacherId,subject,class_group:classGroup})});setSubject('');await refresh()};
 const createWindow=async()=>{if(!subject||!classGroup||!openAt||!closeAt||!session)return;await api('timekeeper_mark_windows',{method:'POST',body:JSON.stringify({subject,class_group:classGroup,opens_at:new Date(openAt).toISOString(),closes_at:new Date(closeAt).toISOString(),created_by:session.user.id})});await refresh()};
 const activeAssignment=assignments.find(a=>a.subject===subject&&a.class_group===classGroup),windowOpen=windows.some(w=>w.subject===subject&&w.class_group===classGroup&&Date.now()>=new Date(w.opens_at).getTime()&&Date.now()<=new Date(w.reopened_until||w.closes_at).getTime());
 const saveMark=async()=>{if(!session||!studentId||!activeAssignment||!assessment||score==='')return;try{await api('timekeeper_marks?on_conflict=student_id,subject,class_group,assessment',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({student_id:studentId,subject,class_group:classGroup,assessment,score:+score,out_of:+outOf,teacher_id:session.user.id,updated_at:new Date().toISOString()})});setScore('');setStatus('Mark saved inside the active marking window.');await refresh()}catch{setStatus('Marks are locked, outside your allocation, or invalid. Ask the administrator to reopen the window.')}};
 const requestWindow=async()=>{if(!session||!subject||!classGroup||!reason)return;await api('timekeeper_window_requests',{method:'POST',body:JSON.stringify({teacher_id:session.user.id,subject,class_group:classGroup,reason})});setReason('');setStatus('Reopening request sent to the administrator.');await refresh()};
 const decide=async(r:RequestRow,approved:boolean)=>{await api(`timekeeper_window_requests?id=eq.${r.id}`,{method:'PATCH',body:JSON.stringify({status:approved?'approved':'rejected'})});if(approved){const until=new Date(Date.now()+24*60*60*1000).toISOString();await api(`timekeeper_mark_windows?subject=eq.${encodeURIComponent(r.subject)}&class_group=eq.${encodeURIComponent(r.class_group)}`,{method:'PATCH',body:JSON.stringify({reopened_until:until})})}await refresh()};
 const teacherAllocations=profile?.role==='teacher'?assignments.filter(a=>a.teacher_id===profile.id):assignments,students=profiles.filter(p=>p.role==='student'),myMarks=profile?.role==='student'?marks.filter(m=>m.student_id===profile.id):marks;
 if(!session)return <section className="settings academicLimited"><h3><LockKeyhole/> Academic access</h3><p className="helper">Sign in under Cloud sync to request a teacher or student profile. Without an approved profile, timetable viewing remains available but marks and administration stay locked.</p></section>;
 if(loading)return <section className="settings"><p className="helper">Loading secure academic access…</p></section>;
 if(!profile)return <section className="settings academicRegistration"><h3><UserRound/> Request school access</h3><p className="helper">Choose your role. An administrator must approve it before protected information becomes visible.</p><label>Role<select value={requestedRole} onChange={e=>setRequestedRole(e.target.value as 'teacher'|'student')}><option value="teacher">Teacher</option><option value="student">Student</option></select></label><label>{requestedRole==='teacher'?'Name exactly as shown in subject allocation':'Student name'}<input value={name} onChange={e=>setName(e.target.value)}/></label>{requestedRole==='student'&&<><label>Student number<input value={studentNumber} onChange={e=>setStudentNumber(e.target.value)}/></label><label>Class/Form<input value={classGroup} onChange={e=>setClassGroup(e.target.value)}/></label></>}<button className="wideTool" onClick={register}>Send access request</button>{status&&<p className="toolStatus">{status}</p>}</section>;
 if(profile.role==='pending')return <section className="settings academicLimited"><h3><Clock3/> Approval pending</h3><p className="helper">Your account is waiting for administrator approval. You can continue using the limited timetable tools, but marks and private school information remain locked.</p></section>;
 if(profile.role==='admin')return <div className="academicPortal"><section className="settings"><h3><ShieldCheck/> Administrator academic controls</h3><p className="helper">Administrators can view every grade and control access and marking windows. Security policies prevent administrators from inserting, editing or deleting marks.</p>{profiles.filter(p=>p.role==='pending').map(p=><div className="approvalRow" key={p.id}><span><b>{p.display_name}</b><small>{p.teacher_name?'Teacher request':'Student request'}</small></span><div><button onClick={()=>approve(p,p.teacher_name?'teacher':'student')}>Approve</button><button onClick={()=>approve(p,'pending')}>Reject</button></div></div>)}</section><section className="settings spaced"><h3><BookOpen/> Teacher subject allocation</h3><div className="suiteGrid"><select value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Teacher</option>{profiles.filter(p=>p.role==='teacher').map(p=><option value={p.id} key={p.id}>{p.display_name}</option>)}</select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><input value={classGroup} onChange={e=>setClassGroup(e.target.value)} placeholder="Class/Form"/><button onClick={allocate}>Allocate</button></div></section><section className="settings spaced"><h3><Clock3/> Marking windows</h3><div className="suiteGrid"><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><input value={classGroup} onChange={e=>setClassGroup(e.target.value)} placeholder="Class/Form"/><input type="datetime-local" value={openAt} onChange={e=>setOpenAt(e.target.value)}/><input type="datetime-local" value={closeAt} onChange={e=>setCloseAt(e.target.value)}/></div><button className="wideTool" onClick={createWindow}>Open marking window</button>{requests.filter(r=>r.status==='pending').map(r=><div className="approvalRow" key={r.id}><span><b>{r.subject} • {r.class_group}</b><small>{r.reason}</small></span><div><button onClick={()=>decide(r,true)}>Reopen 24h</button><button onClick={()=>decide(r,false)}>Reject</button></div></div>)}</section><GradeTable marks={marks} profiles={profiles}/><SchoolSuite/></div>;
 if(profile.role==='student')return <GradeTable marks={myMarks} profiles={[profile]}/>;
 return <div className="academicPortal"><section className="settings"><h3><GraduationCap/> My subject marks</h3><p className="helper">You can only view and enter marks for subjects allocated to your approved teacher account.</p><div className="suiteGrid"><select value={`${subject}|${classGroup}`} onChange={e=>{const [s,c]=e.target.value.split('|');setSubject(s);setClassGroup(c)}}><option value="|">Choose allocated subject</option>{teacherAllocations.map(a=><option value={`${a.subject}|${a.class_group}`} key={a.id}>{a.subject} • {a.class_group}</option>)}</select><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Student</option>{students.filter(s=>!classGroup||clean(s.class_group||'')===clean(classGroup)).map(s=><option value={s.id} key={s.id}>{s.display_name} • {s.student_number}</option>)}</select><input value={assessment} onChange={e=>setAssessment(e.target.value)} placeholder="Assessment, e.g. Midterm"/><input type="number" value={score} onChange={e=>setScore(e.target.value)} placeholder="Score"/><input type="number" value={outOf} onChange={e=>setOutOf(e.target.value)} placeholder="Out of"/></div><button className="wideTool" disabled={!windowOpen} onClick={saveMark}>{windowOpen?'Save or edit mark':'Marks locked by administrator'}</button><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why should the marking window be reopened?"/><button className="wideTool" onClick={requestWindow}>Request window reopening</button>{status&&<p className="toolStatus">{status}</p>}</section><GradeTable marks={marks} profiles={profiles}/></div>;
}

function GradeTable({marks,profiles}:{marks:Mark[];profiles:Profile[]}){return <section className="settings spaced"><h3><Users/> Grades</h3>{marks.map(m=><div className="gradeRow" key={m.id}><span><b>{m.subject} • {m.assessment}</b><small>{profiles.find(p=>p.id===m.student_id)?.display_name||m.class_group} • {m.class_group}</small></span><strong>{m.score}/{m.out_of}</strong></div>)}{!marks.length&&<p className="none">No grades available.</p>}</section>}
