import {Capacitor} from '@capacitor/core';
import {Directory,Filesystem} from '@capacitor/filesystem';
import {loadTimetables} from './storage';

export type SyncState='offline'|'local'|'syncing'|'synced'|'error';
export interface CloudConfig{url:string;key:string}
interface Session{access_token:string;refresh_token:string;expires_at:number;user:{id:string;email?:string}}
interface CloudBackup{format:'timekeeper-cloud-v1';modifiedAt:number;values:Record<string,string>;pdfs:Record<string,string>}
const CONFIG='tk_cloud_config',SESSION='tk_cloud_session',MODIFIED='tk_sync_modified_at';
export const getCloudConfig=():CloudConfig=>{try{return JSON.parse(localStorage.getItem(CONFIG)||'{}')}catch{return{url:'',key:''}}};
export const saveCloudConfig=(value:CloudConfig)=>localStorage.setItem(CONFIG,JSON.stringify({url:value.url.replace(/\/$/,''),key:value.key.trim()}));
export const getCloudSession=():Session|null=>{try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}};
const headers=(config:CloudConfig,token?:string)=>({'apikey':config.key,'Authorization':`Bearer ${token||config.key}`,'Content-Type':'application/json'});
const authRequest=async(path:string,body:unknown)=>{const config=getCloudConfig();if(!config.url||!config.key)throw new Error('Cloud service is not configured.');const response=await fetch(`${config.url}/auth/v1/${path}`,{method:'POST',headers:headers(config),body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.msg||data.error_description||data.message||'Account request failed.');if(data.access_token){const session={...data,expires_at:Math.floor(Date.now()/1000)+(data.expires_in||3600)};localStorage.setItem(SESSION,JSON.stringify(session));return session as Session}return data};
export const signUp=(email:string,password:string)=>authRequest('signup',{email,password});
export const signIn=(email:string,password:string)=>authRequest('token?grant_type=password',{email,password});
export const signOut=()=>localStorage.removeItem(SESSION);
const session=async()=>{let value=getCloudSession();if(!value)return null;if(value.expires_at>Date.now()/1000+60)return value;try{value=await authRequest('token?grant_type=refresh_token',{refresh_token:value.refresh_token});return value}catch{signOut();return null}};
const localBackup=async():Promise<CloudBackup>=>{const values:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('tk_')&&!key.startsWith('tk_cloud_'))values[key]=localStorage.getItem(key)||''}const pdfs:Record<string,string>={};if(Capacitor.isNativePlatform())for(const table of loadTimetables()){try{const file=await Filesystem.readFile({path:`timetables/${table.id}.pdf`,directory:Directory.Data});if(typeof file.data==='string')pdfs[table.id]=file.data}catch{/* no stored source PDF */}}return{format:'timekeeper-cloud-v1',modifiedAt:Number(localStorage.getItem(MODIFIED)||Date.now()),values,pdfs}};
const applyBackup=async(data:CloudBackup)=>{for(const key of Object.keys(localStorage))if(key.startsWith('tk_')&&!key.startsWith('tk_cloud_'))localStorage.removeItem(key);for(const [key,value] of Object.entries(data.values))localStorage.setItem(key,value);localStorage.setItem(MODIFIED,String(data.modifiedAt));if(Capacitor.isNativePlatform())for(const [id,pdf] of Object.entries(data.pdfs||{}))await Filesystem.writeFile({path:`timetables/${id}.pdf`,data:pdf,directory:Directory.Data,recursive:true})};
export const syncNow=async():Promise<'uploaded'|'downloaded'|'current'>=>{if(!navigator.onLine)throw new Error('Offline. Changes are safely stored on this device.');const active=await session();if(!active)throw new Error('Sign in to start cloud sync.');const config=getCloudConfig(),path=`${active.user.id}/backup.json`,download=await fetch(`${config.url}/storage/v1/object/authenticated/timekeeper-sync/${path}`,{headers:headers(config,active.access_token)});let remote:CloudBackup|null=null;if(download.ok)remote=await download.json();else if(download.status!==404)throw new Error('Could not read cloud backup. Check the storage policies.');const local=await localBackup();if(remote&&remote.modifiedAt>local.modifiedAt){await applyBackup(remote);return'downloaded'}if(!remote||local.modifiedAt>remote.modifiedAt){const upload=await fetch(`${config.url}/storage/v1/object/timekeeper-sync/${path}`,{method:'POST',headers:{...headers(config,active.access_token),'x-upsert':'true'},body:JSON.stringify(local)});if(!upload.ok)throw new Error('Could not upload. Check the timekeeper-sync bucket policies.');return'uploaded'}return'current'};
