import {useEffect,useMemo,useState} from 'react';
import QRCode from 'qrcode';
import {BarChart3,BookOpen,CalendarDays,CheckCircle2,FileText,GraduationCap,Languages,LockKeyhole,Plus,QrCode,Share2,ShieldCheck,Users} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {loadActiveTimetable,loadAllocations,loadSettings,loadTimetables,saveActiveTimetable,saveTimetables} from './storage';
import type {ClassItem,Timetable} from './types';
import InvigilationSuite from './invigilationSuite';

const STORE='tk_school_suite',days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],times=[['07:30','08:10'],['08:10','08:50'],['09:10','09:50'],['09:50','10:30'],['10:50','11:30'],['11:30','12:10'],['13:00','13:40'],['13:40','14:20']];
type Attendance={id:string;className:string;date:string;students:{name:string;present:boolean}[]};
type Plan={id:string;classId:string;date:string;objective:string;homework:string;notes:string};
type Exam={id:string;subject:string;className:string;date:string;start:string;room:string;invigilator:string};
type Request={id:string;summary:string;requestedBy:string;status:'pending'|'approved'|'rejected';createdAt:number};
type SuiteData={adminMode:boolean;attendance:Attendance[];plans:Plan[];exams:Exam[];requests:Request[];language:'en'|'ny'};
const defaults:SuiteData={adminMode:false,attendance:[],plans:[],exams:[],requests:[],language:'en'};
const load=():SuiteData=>{try{return{...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return defaults}};
const save=(value:SuiteData)=>{localStorage.setItem(STORE,JSON.stringify(value));localStorage.setItem('tk_modified_at',String(Date.now()))};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const tkey=(v:string)=>v.toLowerCase().replace(/\b(mr|mrs|miss|ms)\b/g,'').replace(/[^a-z]/g,'');

export function AppLock({unlock}:{unlock:()=>void}){const [pin,setPin]=useState(''),[error,setError]=useState('');const stored=localStorage.getItem('tk_app_pin');const check=()=>{if(pin===stored){sessionStorage.setItem('tk_unlocked','1');unlock()}else setError('Incorrect PIN. Try again.')};return <main className="lockScreen"><div className="lockCard"><div className="profileMark"><LockKeyhole/></div><small>TIMEKEEPER SECURITY</small><h1>App locked</h1><p>Enter your TimeKeeper PIN to access school and teacher information.</p><input autoFocus inputMode="numeric" type="password" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} onKeyDown={e=>{if(e.key==='Enter')check()}} aria-label="App PIN" placeholder="PIN"/><button className="primary" disabled={pin.length<4} onClick={check}>Unlock</button>{error&&<p className="toolStatus">{error}</p>}</div></main>}

export default function SchoolSuite(){
 const [data,setData]=useState<SuiteData>(load),[open,setOpen]=useState('admin'),[status,setStatus]=useState(''),tables=loadTimetables().filter(t=>!t.deletedAt),active=tables.find(t=>t.id===loadActiveTimetable())||tables[0],allocations=loadAllocations(),classes=active?.classes||[];
 const update=(next:SuiteData)=>{setData(next);save(next)};
 const [students,setStudents]=useState(''),[attendanceClass,setAttendanceClass]=useState(classes[0]?.room||''),[attendanceDate,setAttendanceDate]=useState(new Date().toISOString().slice(0,10));
 const [planClass,setPlanClass]=useState(classes[0]?.id||''),[objective,setObjective]=useState(''),[homework,setHomework]=useState(''),[notes,setNotes]=useState('');
 const [exam,setExam]=useState<Omit<Exam,'id'>>({subject:'',className:'',date:'',start:'08:00',room:'',invigilator:''}),[request,setRequest]=useState(''),[requester,setRequester]=useState('');
 const [qr,setQr]=useState(''),[transfer,setTransfer]=useState(''),[pin,setPin]=useState('');
 const rooms=[...new Set(classes.map(c=>c.room).filter(Boolean))],teachers=[...new Map(allocations.map(a=>[tkey(a.teacher),a.teacher])).values()];
 const stats=useMemo(()=>({periods:classes.length,teachers:new Set(classes.map(c=>tkey(c.teacher)).filter(Boolean)).size,classes:new Set(classes.map(c=>c.room).filter(Boolean)).size,subjects:new Set(classes.map(c=>c.subject)).size,free:Math.max(0,5*times.length-classes.length)}),[classes]);
 const generate=()=>{if(!allocations.length){setStatus('Upload a subject allocation before generating a timetable.');return}const forms=[...new Set(allocations.map(a=>a.classGroup).filter(Boolean))] as string[];if(!forms.length){setStatus('Allocations need Form/Class names before automatic generation.');return}const teacherBusy=new Set<string>(),items:ClassItem[]=[];for(const form of forms){let cursor=0;for(const allocation of allocations.filter(a=>a.classGroup===form)){let placed=false;for(let attempt=0;attempt<40&&!placed;attempt++){const day=1+(cursor%5),slot=Math.floor(cursor/5)%times.length,busy=`${tkey(allocation.teacher)}:${day}:${slot}`;cursor++;if(teacherBusy.has(busy))continue;teacherBusy.add(busy);items.push({id:uid(),subject:allocation.subject,room:form,teacher:allocation.teacher,day,start:times[slot][0],end:times[slot][1],color:['#2459c4','#16856b','#a96018','#9e3f47'][items.length%4],enabled:true});placed=true}}}const table:Timetable={id:uid(),name:`Generated timetable ${tables.length+1}`,classes:items,file:null,createdAt:Date.now(),allocations,teacherName:'',classGroup:'',scheduleFilter:'all',remindersEnabled:true};saveTimetables([...tables,table]);saveActiveTimetable(table.id);setStatus(`Generated ${items.length} periods without teacher clashes. Reloading…`);setTimeout(()=>location.reload(),500)};
 const addAttendance=()=>{const names=students.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(!attendanceClass||!names.length)return;update({...data,attendance:[{id:uid(),className:attendanceClass,date:attendanceDate,students:names.map(name=>({name,present:true}))},...data.attendance]});setStudents('')};
 const toggleStudent=(recordId:string,name:string)=>update({...data,attendance:data.attendance.map(r=>r.id!==recordId?r:{...r,students:r.students.map(s=>s.name!==name?s:{...s,present:!s.present})})});
 const addPlan=()=>{if(!planClass||!objective.trim())return;update({...data,plans:[{id:uid(),classId:planClass,date:new Date().toISOString().slice(0,10),objective,homework,notes},...data.plans]});setObjective('');setHomework('');setNotes('')};
 const addExam=()=>{if(!exam.subject||!exam.date||!exam.className)return;update({...data,exams:[{...exam,id:uid()},...data.exams]});setExam({...exam,subject:'',className:'',date:''})};
 const addRequest=()=>{if(!request.trim())return;update({...data,requests:[{id:uid(),summary:request,requestedBy:requester||'Teacher',status:'pending',createdAt:Date.now()},...data.requests]});setRequest('')};
 const makeQr=async()=>{if(!active)return;const payload=JSON.stringify({type:'timekeeper-timetable',version:1,table:{...active,file:null}});setTransfer(payload);setQr(await QRCode.toDataURL(payload,{width:280,margin:2,errorCorrectionLevel:'M'}))};
 const importTransfer=()=>{try{const parsed=JSON.parse(transfer) as {type:string;table:Timetable};if(parsed.type!=='timekeeper-timetable'||!parsed.table?.classes)throw new Error();const table={...parsed.table,id:uid(),name:`${parsed.table.name} (received)`,createdAt:Date.now()};saveTimetables([...tables,table]);saveActiveTimetable(table.id);setStatus('Received timetable saved. Reloading…');setTimeout(()=>location.reload(),500)}catch{setStatus('That transfer code is not a valid TimeKeeper timetable.')}};
 const nearby=async()=>{if(!transfer)await makeQr();const text=transfer||JSON.stringify({type:'timekeeper-timetable',version:1,table:{...active,file:null}});if(Capacitor.isNativePlatform())await Share.share({title:active?.name||'TimeKeeper timetable',text,dialogTitle:'Send to a nearby device'});else if(navigator.share)await navigator.share({title:active?.name,text})};
 const enablePin=()=>{if(pin.length<4){setStatus('Use a PIN containing 4 to 6 digits.');return}localStorage.setItem('tk_app_pin',pin);sessionStorage.setItem('tk_unlocked','1');setPin('');setStatus('App lock enabled. It will be required the next time the app starts.')};
 const removePin=()=>{localStorage.removeItem('tk_app_pin');sessionStorage.removeItem('tk_unlocked');setStatus('App lock removed.')};
 const labels=data.language==='ny'?{title:'Zida za sukulu',admin:'Kasamalidwe',generator:'Pangani ndandanda',attendance:'Kalondolondo',plans:'Mapulani a maphunziro',exams:'Mayeso'}:{title:'School Suite',admin:'Administrator mode',generator:'Automatic timetable generator',attendance:'Attendance register',plans:'Lesson planning',exams:'Examination timetable'};
 const panel=(id:string,title:string,icon:React.ReactNode,body:React.ReactNode)=><section className="settings suitePanel"><button className="suiteHead" onClick={()=>setOpen(open===id?'':id)} aria-expanded={open===id}>{icon}<span><b>{title}</b><small>{open===id?'Tap to close':'Tap to manage'}</small></span><Plus/></button>{open===id&&<div className="suiteBody">{body}</div>}</section>;
 return <div className="schoolSuite"><div className="pageTitle"><div><small>ADVANCED MODULES</small><h1>{labels.title}</h1></div></div>
 {panel('admin',labels.admin,<ShieldCheck/>,<><label className="switchRow"><span><b>Administrator controls</b><small>View and coordinate the whole school timetable.</small></span><input type="checkbox" checked={data.adminMode} onChange={e=>update({...data,adminMode:e.target.checked})}/></label><div className="suiteStats"><span><b>{tables.length}</b><small>timetables</small></span><span><b>{teachers.length}</b><small>teachers</small></span><span><b>{rooms.length}</b><small>classes</small></span></div>{teachers.map(name=><div className="suiteRow" key={name}><b>{name}</b><small>{allocations.filter(a=>tkey(a.teacher)===tkey(name)).length} allocations</small></div>)}</>)}
 {panel('generator',labels.generator,<CalendarDays/>,<><p className="helper">Builds a balanced draft from class allocations while preventing a teacher from occupying two classes at once.</p><button className="wideTool" onClick={generate}>Generate conflict-free draft</button></>)}
 {panel('attendance',labels.attendance,<Users/>,<><label>Class<select value={attendanceClass} onChange={e=>setAttendanceClass(e.target.value)}>{rooms.map(x=><option key={x}>{x}</option>)}</select></label><label>Date<input type="date" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/></label><label>Student names<textarea value={students} onChange={e=>setStudents(e.target.value)} placeholder="One name per line"/></label><button className="wideTool" disabled={!attendanceClass||!students.trim()} onClick={addAttendance}>Create attendance register</button>{data.attendance.slice(0,5).map(r=><details className="compactDetails" key={r.id}><summary><span><b>{r.className} • {r.date}</b><small>{r.students.filter(s=>s.present).length}/{r.students.length} present</small></span></summary><div className="detailsList">{r.students.map(s=><label className="studentRow" key={s.name}><input type="checkbox" checked={s.present} onChange={()=>toggleStudent(r.id,s.name)}/>{s.name}</label>)}</div></details>)}</>)}
 {panel('plans',labels.plans,<BookOpen/>,<><label>Lesson<select value={planClass} onChange={e=>setPlanClass(e.target.value)}>{classes.map(c=><option value={c.id} key={c.id}>{c.room} • {c.subject}</option>)}</select></label><label>Learning objective<textarea value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>Homework<input value={homework} onChange={e=>setHomework(e.target.value)}/></label><label>Teacher notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="wideTool" disabled={!objective.trim()} onClick={addPlan}>Save lesson plan</button>{data.plans.slice(0,5).map(p=><div className="suiteRow" key={p.id}><b>{classes.find(c=>c.id===p.classId)?.subject||'Lesson'} • {p.date}</b><small>{p.objective}</small></div>)}</>)}
 {panel('exams',labels.exams,<GraduationCap/>,<><div className="suiteGrid"><input placeholder="Subject" value={exam.subject} onChange={e=>setExam({...exam,subject:e.target.value})}/><input placeholder="Class/Form" value={exam.className} onChange={e=>setExam({...exam,className:e.target.value})}/><input type="date" value={exam.date} onChange={e=>setExam({...exam,date:e.target.value})}/><input type="time" value={exam.start} onChange={e=>setExam({...exam,start:e.target.value})}/><input placeholder="Room" value={exam.room} onChange={e=>setExam({...exam,room:e.target.value})}/><input placeholder="Invigilator" value={exam.invigilator} onChange={e=>setExam({...exam,invigilator:e.target.value})}/></div><button className="wideTool" onClick={addExam}>Add examination</button>{data.exams.map(x=><div className="suiteRow" key={x.id}><b>{x.subject} • {x.className}</b><small>{x.date} {x.start} • {x.room} • {x.invigilator}</small></div>)}</>)}
 <InvigilationSuite/>
 {panel('approval','Change approval workflow',<CheckCircle2/>,<><input value={requester} onChange={e=>setRequester(e.target.value)} placeholder="Requested by"/><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe substitution or timetable change"/><button className="wideTool" onClick={addRequest}>Submit change request</button>{data.requests.map(r=><div className="approvalRow" key={r.id}><span><b>{r.summary}</b><small>{r.requestedBy} • {r.status}</small></span>{r.status==='pending'&&<div><button onClick={()=>update({...data,requests:data.requests.map(x=>x.id===r.id?{...x,status:'approved'}:x)})}>Approve</button><button onClick={()=>update({...data,requests:data.requests.map(x=>x.id===r.id?{...x,status:'rejected'}:x)})}>Reject</button></div>}</div>)}</>)}
 {panel('qr','QR timetable transfer',<QrCode/>,<><p className="helper">Create an offline transfer QR and code. The receiving phone can paste the decoded code below.</p><button className="wideTool" onClick={makeQr}>Generate transfer QR</button>{qr&&<img className="transferQr" src={qr} alt="Timetable transfer QR code"/>}<textarea value={transfer} onChange={e=>setTransfer(e.target.value)} placeholder="Transfer code"/><button className="wideTool" disabled={!transfer} onClick={importTransfer}>Import transfer code</button></>)}
 {panel('nearby','Nearby offline sharing',<Share2/>,<><p className="helper">Uses Android’s sharing panel with Bluetooth, Quick Share or another locally available app.</p><button className="wideTool" disabled={!active} onClick={nearby}>Send active timetable nearby</button></>)}
 {panel('widget','Home-screen widget',<CalendarDays/>,<><p className="helper">The Android widget displays a TimeKeeper shortcut for today’s timetable. Add it by holding an empty area of the home screen and choosing Widgets → TimeKeeper Master.</p><div className="widgetPreview"><small>NEXT LESSON</small><b>{classes[0]?.subject||'No lesson selected'}</b><span>{classes[0]?`${classes[0].start} • ${classes[0].room}`:'Open TimeKeeper to view today'}</span></div></>)}
 {panel('statistics','Statistics dashboard',<BarChart3/>,<><div className="suiteStats dashboard"><span><b>{stats.periods}</b><small>periods</small></span><span><b>{stats.teachers}</b><small>teachers</small></span><span><b>{stats.classes}</b><small>classes</small></span><span><b>{stats.subjects}</b><small>subjects</small></span><span><b>{stats.free}</b><small>free slots</small></span></div>{teachers.slice(0,10).map(name=><div className="barRow" key={name}><span>{name}</span><i style={{width:`${Math.min(100,classes.filter(c=>tkey(c.teacher)===tkey(name)).length*10)}%`}}/><b>{classes.filter(c=>tkey(c.teacher)===tkey(name)).length}</b></div>)}</>)}
 {panel('security','Data protection and app lock',<LockKeyhole/>,<><p className="helper">A local PIN protects access. Cloud credentials remain in this app’s private storage.</p><input type="password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="4–6 digit PIN"/><div className="toolButtons"><button onClick={enablePin}>Enable or change PIN</button><button onClick={removePin}>Remove PIN</button></div></>)}
 {panel('language','Language',<Languages/>,<><label>Application language<select value={data.language} onChange={e=>update({...data,language:e.target.value as SuiteData['language']})}><option value="en">English</option><option value="ny">Chichewa</option></select></label><p className="helper">School subject names and imported timetable wording are always preserved exactly as entered.</p></>)}
 {status&&<p className="toolStatus">{status}</p>}</div>;
}
