import {Capacitor} from '@capacitor/core';
import {Directory,Filesystem} from '@capacitor/filesystem';
import type {Allocation,ClassItem,Settings,StoredFile,Timetable} from './types';
const CLASSES='tk_classes',SETTINGS='tk_settings',FILE='tk_file',ALLOCATIONS='tk_allocations',TIMETABLES='tk_timetables',ACTIVE='tk_active_timetable',HISTORY='tk_history';
const touch=()=>localStorage.setItem('tk_sync_modified_at',String(Date.now()));
export const defaults:Settings={leadMinutes:10,mode:'both',weekends:false,theme:'system',displayName:'',teacherName:'',classGroup:'',scheduleFilter:'mine',onboardingDone:false,schoolName:'',schoolLogo:'',alertSound:'timekeeper',fontScale:1,highContrast:false,reduceMotion:false,calendarExceptions:[]};
const read=<T>(key:string,fallback:T):T=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback}catch{return fallback}};
export const loadClasses=():ClassItem[]=>read(CLASSES,[]);
export const saveClasses=(v:ClassItem[])=>{localStorage.setItem(CLASSES,JSON.stringify(v));touch()};
export const loadFile=():StoredFile|null=>read(FILE,null);
export const loadAllocations=():Allocation[]=>read(ALLOCATIONS,[]);
export const loadSettings=():Settings=>({...defaults,...read<Partial<Settings>>(SETTINGS,{})});
const complete=(t:Partial<Timetable>,legacyAllocations:Allocation[],legacySettings:Settings,index:number):Timetable=>({id:t.id||`migrated-${index+1}`,name:t.name||`Timetable ${index+1}`,classes:Array.isArray(t.classes)?t.classes:[],file:t.file||null,createdAt:t.createdAt||Date.now(),allocations:Array.isArray(t.allocations)?t.allocations:legacyAllocations,teacherName:t.teacherName??legacySettings.teacherName,classGroup:t.classGroup??legacySettings.classGroup,scheduleFilter:t.scheduleFilter||legacySettings.scheduleFilter||'mine',remindersEnabled:t.remindersEnabled!==false});
export const loadTimetables=():Timetable[]=>{const allocations=loadAllocations(),settings=loadSettings(),saved=read<Partial<Timetable>[]>(TIMETABLES,[]);if(saved.length)return saved.map((t,i)=>complete(t,allocations,settings,i));const classes=loadClasses(),file=loadFile();return classes.length||file?[complete({id:'legacy',name:'Timetable 1',classes,file,createdAt:file?.addedAt},allocations,settings,0)]:[]};
export const saveTimetables=(v:Timetable[])=>{const next=JSON.stringify(v),previous=localStorage.getItem(TIMETABLES);if(previous&&previous!==next){const history=read<{id:string;createdAt:number;tables:Timetable[]}[]>(HISTORY,[]);try{const tables=JSON.parse(previous) as Timetable[];history.unshift({id:`history-${Date.now()}`,createdAt:Date.now(),tables});localStorage.setItem(HISTORY,JSON.stringify(history.slice(0,10)))}catch{/* Ignore an unreadable legacy snapshot. */}}localStorage.setItem(TIMETABLES,next);touch()};
export const loadActiveTimetable=()=>localStorage.getItem(ACTIVE)||'';
export const saveActiveTimetable=(id:string)=>id?localStorage.setItem(ACTIVE,id):localStorage.removeItem(ACTIVE);
export const saveSettings=(v:Settings)=>{localStorage.setItem(SETTINGS,JSON.stringify(v));touch()};
export const saveAllocations=(v:Allocation[])=>{localStorage.setItem(ALLOCATIONS,JSON.stringify(v));touch()};
export const saveFile=async(v:StoredFile,id='legacy')=>{localStorage.setItem(FILE,JSON.stringify({...v,data:''}));if(Capacitor.isNativePlatform())await Filesystem.writeFile({path:`timetables/${id}.pdf`,data:v.data,directory:Directory.Data,recursive:true});else localStorage.setItem(FILE,JSON.stringify(v))};
export const getShareUri=async(id='legacy')=>{if(!Capacitor.isNativePlatform())return '';try{return(await Filesystem.getUri({path:`timetables/${id}.pdf`,directory:Directory.Data})).uri}catch{if(id==='legacy')return(await Filesystem.getUri({path:'timetable.pdf',directory:Directory.Data})).uri;throw new Error('Stored PDF is unavailable')}};
export const deleteTimetableFile=async(id:string)=>{if(!Capacitor.isNativePlatform())return;try{await Filesystem.deleteFile({path:`timetables/${id}.pdf`,directory:Directory.Data})}catch{/* Already absent. */}};
export const clearAll=async()=>{if(Capacitor.isNativePlatform()){try{await Filesystem.rmdir({path:'timetables',directory:Directory.Data,recursive:true})}catch{/* Already absent. */}try{await Filesystem.deleteFile({path:'timetable.pdf',directory:Directory.Data})}catch{/* Already absent. */}}[CLASSES,FILE,ALLOCATIONS,TIMETABLES,ACTIVE].forEach(k=>localStorage.removeItem(k))};
