import {useEffect,useState} from 'react';
import {CheckCircle2,Download,RefreshCw,ShieldCheck} from 'lucide-react';

const CURRENT_CODE=3,CURRENT_NAME='1.2.0';
const MANIFEST_URL='https://raw.githubusercontent.com/ClementMasauko/clement-masauko/main/update.json';
type Release={versionCode:number;versionName:string;minimumVersionCode?:number;required?:boolean;apkUrl:string;notes?:string[];sha256?:string;publishedAt?:string};

export default function UpdatePanel(){
 const [release,setRelease]=useState<Release|null>(null),[state,setState]=useState<'idle'|'checking'|'current'|'available'|'offline'|'error'>('idle'),[message,setMessage]=useState('');
 const check=async(silent=false)=>{setState('checking');if(!navigator.onLine){setState('offline');if(!silent)setMessage('Offline. Update checking will work when internet returns.');return}try{const response=await fetch(`${MANIFEST_URL}?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(response.status===404?'The GitHub release repository is not published yet.':'The update service could not be reached.');const next=await response.json() as Release;if(!next.versionCode||!next.apkUrl)throw new Error('The update information is incomplete.');setRelease(next);if(next.versionCode>CURRENT_CODE){setState('available');setMessage(`Version ${next.versionName} is ready to download.`)}else{setState('current');setMessage('You already have the latest version.')}}catch(error){setState('error');if(!silent)setMessage(error instanceof Error?error.message:'Could not check for updates.')}};
 useEffect(()=>{void check(true)},[]);
 const download=()=>{if(!release?.apkUrl)return;localStorage.setItem('tk_update_downloaded',String(Date.now()));window.open(release.apkUrl,'_blank','noopener,noreferrer')};
 return <section className={`settings updatePanel ${state==='available'?'updateAvailable':''}`}><div className="settingHead"><h3>{state==='available'?<Download/>:<RefreshCw/>} App updates</h3><span className={`syncBadge ${state==='available'?'error':state==='current'?'synced':'local'}`}>{state==='checking'?'Checking…':state==='available'?'Update available':state==='current'?'Up to date':'Version '+CURRENT_NAME}</span></div><p className="helper">Checks the official TimeKeeper GitHub release page. Your timetable continues working normally without internet.</p>{state==='available'&&release&&<div className="releaseCard"><div><b>TimeKeeper Master {release.versionName}</b><small>{release.required||CURRENT_CODE<(release.minimumVersionCode||0)?'Important update':'Optional update'}</small></div>{release.notes?.length?<ul>{release.notes.map(note=><li key={note}>{note}</li>)}</ul>:null}{release.sha256&&<small className="checksum">SHA-256: {release.sha256}</small>}<button className="primary" onClick={download}><Download/> Download signed update</button><p><ShieldCheck/> Android will ask you to approve installation. Existing app data is preserved.</p></div>}{state==='current'&&<div className="note"><CheckCircle2/><p><b>Latest version installed</b><span>TimeKeeper Master {CURRENT_NAME}</span></p></div>}<button className="wideTool" disabled={state==='checking'} onClick={()=>check(false)}><RefreshCw/> Check for updates</button>{message&&state!=='current'&&<p className="toolStatus">{message}</p>}</section>;
}
